apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: api-images-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod
  source:
    repoURL: 'https://github.com/Adenilson365/devopslabs01-ops-api-images.git'
    targetRevision: main
    path: application 
    directory:
      recurse: true
  destination:
    server: 'https://35.229.67.82'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true