apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: api-frontend-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod
  source:
    repoURL: 'https://github.com/Adenilson365/devopslabas01-ops-frontend.git'
    targetRevision: main
    path: application 
    directory:
      recurse: true
  destination:
    server: 'https://35.196.226.32'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true