apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-frontend-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod
  source:
    repoURL: "https://github.com/Adenilson365/devopslabas01-ops-frontend.git"
    targetRevision: main
    path: application
    directory:
      recurse: true
  destination:
    server: "https://34.23.65.53"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
