apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: argo-mgmt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd
  source:
    repoURL: 'https://github.com/Adenilson365/argocd-lab.git'
    targetRevision: HEAD
    path: argo-mgmt/k8s-mgmt/infra
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true