apiVersion: v1
kind: Pod
metadata:
  name: gcloud-test
  namespace: external-secrets
spec:
  serviceAccountName: eso-secret-accessor # KSA com Workload Identity
  containers:
    - name: gcloud
      image: google/cloud-sdk:slim
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "🔐 Testando acesso ao Secret Manager..."
          gcloud secrets versions access latest --secret="db-credentials"
      env:
        - name: GOOGLE_PROJECT
          value: "argo-dev-455710"
      tty: true
