apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: api-mgmt-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adenilson365/argocd-lab.git'
    targetRevision: HEAD
    path: dev
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true