apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: api-catalogo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adenilson365/devopslabs01-ops-catalogo.git'
    targetRevision: HEAD
    path: application 
    directory:
      recurse: true
  destination:
    server: 'https://35.238.176.235'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true