apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-manisfests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: "https://github.com/Adenilson365/devops-labs01-config.git"
    targetRevision: HEAD
    path: dev
    directory:
      recurse: true
  destination:
    server: "https://34.23.65.53"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
