apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: shared-manisfests-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod
  source:
    repoURL: 'https://github.com/Adenilson365/devops-labs01-config.git'
    targetRevision: HEAD
    path: prod
    directory:
      recurse: true
  destination:
    server: 'https://35.196.226.32'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true