apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Projeto de desenvolvimento
  sourceRepos:
    - https://github.com/Adenilson365/devopslabs01-ops-api-images.git
    - https://github.com/Adenilson365/devopslabs01-ops-catalogo.git
    - https://github.com/Adenilson365/devopslabas01-ops-frontend.git
    - https://charts.jetstack.io
    - https://kubernetes.github.io/ingress-nginx
    - https://github.com/Adenilson365/devops-labs01-config.git
    - https://github.com/Adenilson365/argocd-lab.git
    - https://charts.external-secrets.io
  destinations:
    - server: https://104.154.208.114
      namespace: "*"
    - server: https://kubernetes.default.svc
      namespace: "argocd"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
