apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  description: Projeto de desenvolvimento
  sourceRepos:
    - https://charts.jetstack.io
    - https://kubernetes.github.io/ingress-nginx
    - https://github.com/Adenilson365/devops-labs01-config.git
    - https://github.com/Adenilson365/argocd-lab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
