apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: cert-manager
  namespace: argocd
spec:
  project: dev
  source: 
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.17.0
    helm:
      releaseName: cert-manager
      parameters:
        - name: installCRDs
          value: "true"

  destination:
    server: 'https://35.238.176.235'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

#DOC: https://cert-manager.io/docs/installation/helm/