apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eternal-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: "https://charts.external-secrets.io"
    chart: external-secrets
    targetRevision: 0.17.0
    helm:
      releaseName: external-secrets
      parameters:
        - name: installCRDs
          value: "true"

  destination:
    server: "https://104.154.208.114"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
