apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-images
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: "https://github.com/Adenilson365/devopslabs01-ops-api-images.git"
    targetRevision: dev
    path: application
    directory:
      recurse: true
  destination:
    server: "https://35.185.125.78"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
