apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-catalogo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: "https://github.com/Adenilson365/devopslabs01-ops-catalogo.git"
    targetRevision: dev
    path: application
    directory:
      recurse: true
  destination:
    server: "https://34.31.234.5"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
